export const VIDEOS_DATA = [
  {
    id: "video1",
    title: "सोनगढ़ प्रतिकृति का भव्य शिलान्यास उत्सव- पत्रिका लेखन समारंभ",
    description: "",
    youtubeId: "yPgZhsTTXi8",
    thumbnail: "https://img.youtube.com/vi/yPgZhsTTXi8/maxresdefault.jpg",
  },
  {
    id: "video2",
    title: "मंगल गीत - श्री सोनगढ़ प्रतिकृति शिलान्यास महोत्सव",
    description: "",
    youtubeId: "iv97P4YV40E",
    thumbnail: "/songadh_pratikruti.jpg",
    date: "",
  },
  {
    id: "video3",
    title: "श्री सोनगढ़ प्रतिकृति शिलान्यास महोत्सव पूर्व बेला",
    description: "",
    youtubeId: "4f2DSxV10RM",
    thumbnail: "https://img.youtube.com/vi/4f2DSxV10RM/maxresdefault.jpg",
    date: "",
  },
  {
    id: "video4",
    title: "श्री सोनगढ़ प्रतिकृति शिलान्यास महोत्सव",
    description: "",
    youtubeId: "BHvaM-bCmyI",
    thumbnail: "https://img.youtube.com/vi/BHvaM-bCmyI/maxresdefault.jpg",
    date: "",
  },
  {
    id: "video5",
    title: "वार्षिकोत्सव एवम मानस्तम्भ शिलान्यास महोत्सव",
    description: "",
    youtubeId: "OtozP8XScQU",
    thumbnail: "https://img.youtube.com/vi/OtozP8XScQU/maxresdefault.jpg",
    date: "2.3.2025",
  },
  {
    id: "video6",
    title: "मंगल गीत-  मानस्तम्भ शिलान्यास",
    description: "",
    youtubeId: "QuxdFUMg9DA",
    thumbnail: "https://img.youtube.com/vi/QuxdFUMg9DA/maxresdefault.jpg",
    date: "2.3.2025",
  },
];